import numpy as np
rand_num = np.random.randn()
def Guessing_Game():
    gess=int(input("Enter your guess number: "))
    return gess
def main_menu():            
    """
    Main menu of the game
    """    
    print("Welcome to the Guessing Game!")
    print("Try to guess the number generated by the system.")
    print("Good luck!\n")
    gess=Guessing_Game()
    if rand_num > 0 and gess > 0:
        print("Congratulations! You guessed a positive number correctly!")  
    elif rand_num <= 0 and gess <= 0:
        print("Congratulations! You guessed a non-positive number correctly!")
    else:
        print("Sorry, your guess was incorrect. Better luck next time!")
        print("Thank you for playing! Goodbye!")
    print("Thank you for playing! Goodbye!")
    return          
if __name__ == "__main__":
    main_menu() 


    
      